accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup

app_name = "accounts"

urlpatterns= [
    path('signup/', signup, name = 'signup'),
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'accounts/logout.html'), name='logout'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
]

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike, PhotoFavorite,PhotoLikeList, PhotoFavoriteList

app_name = "photo"
urlpatterns=[
    path("create/", PhotoCreate.as_view(), name='create'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name='like'),
    path("favorite/<int:photo_id>/", PhotoFavorite.as_view(), name='favorite'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("like/", PhotoLikeList.as_view(), name="like_list"),
    path("favorite/", PhotoFavoriteList.as_view(), name="favorite_list"),
    path("", PhotoList.as_view(), name='index'),
]


from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class SignUpForm(forms.ModelForm):

    password = forms.CharField(label = 'Password', widget =forms.PasswordInput)
    Repeat_password = forms.CharField(label='Repeat_password', widget=forms.PasswordInput)



    class Meta:
        model = User
        fields = ['username', 'password','Repeat_password', 'first_name','last_name', 'email',]



def clean_Repeat_password(self):
    cd = self.cleaned_data
    if cd['password'] != cd['Repeat_password']:
        raise forms.ValidationError('비밀번호가 일치하지 않습니다.')
    return cd['Repeat_password']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import SignUpForm
from django.contrib.auth import login

def signup(request):
    if request.method == 'POST':
        #입력받은 내용을 이용해서 회원의 객체를 생성함
        signup_form = SignUpForm(request.POST)

        if signup_form.is_valid():
            user_instance = signup_form.save(commit = False)
            user_instance.set_password(signup_form.cleaned_data['password'])
            user_instance.save()
            return render(request, 'accounts/signup_complete.html', {'username':user_instance.username})

    else:
        signup_form = SignUpForm()
    
    return render(request, 'accounts/signup.html', {'form':signup_form.as_p})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class ="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            Please enter your login information. </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="login" class= 'btn btn-outline-primary'>
        </form>
    </div>
    <div class="col"></div>

</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            logout success. </div>
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class=row>
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post">
            <div class="alert alert-info">Please enter your account information</div>
                    {% csrf_token %}
            <label>Username : <input type="text" name="username"></label>
            <label>Password : <input type="password" name="password"></label>
            <label>Repeat Password : <input type="password" name="password2"></label>
        <input type="submit" value="회원가입" class="btn btn-primary">
        </form>
    </div>
    <div class='col'></div>

</div>

{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
 
{% block content %}

<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary" role ="alert">
            you are succesfully signed</div>
            <a href ="{% url 'account:login' }">Move to login</a>
    </div>
    <div class="col"></div>
</div>

{% endblock %}