accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup

app_name = "accounts"

urlpatterns= [
    path('signup/', signup, name = 'signup'),
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'accounts/logout.html'), name='logout'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
]

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike, PhotoFavorite,PhotoLikeList, PhotoFavoriteList

app_name = "photo"
urlpatterns=[
    path("create/", PhotoCreate.as_view(), name='create'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name='like'),
    path("favorite/<int:photo_id>/", PhotoFavorite.as_view(), name='favorite'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("like/", PhotoLikeList.as_view(), name="like_list"),
    path("favorite/", PhotoFavoriteList.as_view(), name="favorite_list"),
    path("", PhotoList.as_view(), name='index'),
]


from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse



class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'user') #ForeignKey 를 사용해서 User 테이블과 관계를만듦. User? 장고에서 기본적으로 사용하는 사용자모델 ondelete 는 모델 삭제시 값을 어떻게할것이냐의것
    text = models.TextField(blank=True) #text 필드 문자열 길이 제한 x
    image = models.ImageField(upload_to = 'timeline_photo/%Y/%m/%d') #알아서 등록날짜랑 등록일 처리
    created = models.DateTimeField(auto_now_add = True) #글을 작성할때 시간을 가지고 경로에 맞게끔 값을 넣어줌
    updated = models.DateTimeField(auto_now = True) #글 수정일을 저장하기위한 날짜 필드 ,, 객체가 수정될때마다 자동으로 값을 설정해준다

    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def __str__(self):
        return "text : "+self.text 


    class Meta:
        ordering = ['-created'] #ordering 변수는 객체들을 어떤기준으로 정렬할것인지 설정하는옵션

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id]) #상세페이지로 이동하도록 absolute url 설정 이후에 views에서 return super가 나오면 자동적으로 실행

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Photo

class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list' #메인에서 보여줄 로직

class PhotoCreate(CreateView):
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_create'
    success_url = '/'
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form' : form})


class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_update'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):#dispatch 보안상 권한 문제를 해결하기 위함.
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
            #삭제 페이지에서 권한이 없다 라고 띄우거나
            #detail 페이지로 들어가서 삭제에 실패했습니다 라고 띄우거나
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)


from django.http import HttpResponseRedirect
from django.contrib import messages


class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete' 
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):#dispatch 보안상 권한 문제를 해결하기 위함.
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
            #삭제 페이지에서 권한이 없다 라고 띄우거나
            #detail 페이지로 들어가서 삭제에 실패했습니다 라고 띄우거나
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)


class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'
    

from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

class PhotoLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated: #로그인검사
            return HttpResponseForbidden() #거부
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id) #photo에 photo id 넣어줌
                user = request.user
                if user in photo.like.all(): #만약 이미 좋아요가 눌러져있으면 제거함.
                    photo.like.remove(user)
                else:
                    photo.like.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path= urlparse(referer_url).path
            return HttpResponseRedirect(path) #메인페이지에 위치해있다면 그 메인페이지에 있게하고 상세페이지에서 좋아요를 누르면 그 상세페이지로 redirect

class PhotoFavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:    #로그인확인
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.favorite.all():
                    photo.favorite.remove(user)
                else:
                    photo.favorite.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)



class PhotoLikeList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self,request,*args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인 후 이용가능합니다.')
            return HttpResponseRedirect('/')
        return super(PhotoLikeList,self).dispatch(request,*args,**kwargs)
    
    def get_queryset(self):
        #내가 좋아요한 글 보여주기
        user = self.request.user
        queryset = user.like_post.all()
        return queryset

class PhotoFavoriteList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self,request,*args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인 후 이용가능합니다.')
            return HttpResponseRedirect('/')
        return super(PhotoFavoriteList,self).dispatch(request,*args,**kwargs)
    
    def get_queryset(self):
        #내가 저장한글 보여주기
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset

from django.shortcuts import render
from django.contrib.auth.models import User

def signup(request):
    if request.method == 'POST':
        #입력받은 내용을 이용해서 회원의 객체를 생성함
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        #회원 객체 생성하기
        user = User()
        user.username = username
        user.set_password(password)
        user.save()

        return render(request, 'accounts/signup_complete.html')
    
    else:
        #from 객체를 만들어서 전달
        context_values = {'form': 'this is form'}
        return render(request, 'accounts/signup.html', context_values)

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워주세요.
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}
<!-- 진짜 지울건지 확인받아야함. form을 또 보여줄 필요가없다-->

<div class="alert alert-primary" role="alert">
    진짜로 {{object}}를 지우실건가요?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete OK">
</form>

{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width:30rem;">
            <img src=" {{ object.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">

                <h5 class="card-title">{{object.author}}</h5>
                <p class="card-text"> {{object.text}}</p>
            </div>
            <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all %} active {%endif%}">좋아요</a>
                        {% if object.like.all.count %}
                        <span class="float-left">
                            {{object.like.all.count}}
                        </span>
                        {%endif%}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {%if user in object.favorite.all %}active{%endif%}">저장하기</a>
                    </li>
                    {% endif %}
                <li class="list-group-item">수정일 : {{ object.updated}}</li>
                <li class="list-group-item">생성일 : {{ object.created}}</li>
                
            </ul>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
 
{% block content %}

<div class= 'container'>
    <div class = "row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    {{object.author}}
                </div>
                <img src="{{ object.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text"> {{ object.text }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all %} active {%endif%}">좋아요</a>
                        {% if object.like.all.count %}
                        <span class="float-left">
                            {{object.like.all.count}}
                        </span>
                        {%endif%}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {%if user in object.favorite.all %}active{%endif%}">저장하기</a>
                    </li>
                    {% endif %}
                    <li class="list-group-item">생성일: {{object.created}}</li>
                    
                </ul>
                <div class="card-body">
                    {% if user == object.author %}
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">삭제하기</a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" class="card-link">로그인 후 가능합니다.</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="col"></div>
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}